Revert "Add NvmeU2 and Status CPU discrete sensor"
This reverts commit 35dc71340ae686ef6bb3b19644ce6ae08f967585,
which fixes JIRA https://jirasw.nvidia.com/browse/DGXOPENBMC-4609

This is because this causes a build break with the version bump.

ERROR: dbus-sensors-0.1+gitAUTOINC+35dc71340a-r0 do_package:
QA Issue: dbus-sensors: Files/directories were installed but not shipped in any package:
  /lib/systemd/system/xyz.openbmc_project.processorstatus.service
  /lib/systemd/system/xyz.openbmc_project.nvmestatus.service